### PR TITLE
Expands platform support to include macOS, watchOS, and tvOS.

### PR DESCRIPTION
**Pull request by Richard-Gist**
## Checklist:
- [x] Did you sign the [Contributor License Agreement](https://cla-assistant.io/wwt/SwiftCurrent)?
- [x] Is the linter reporting 0 errors?
- [x] Does the CI pipeline pass?
- [x] Did you [update the documentation](https://github.com/wwt/SwiftCurrent/blob/main/.github/CONTRIBUTING.md#documentation)?
- [x] Do we need to [increment the minor/major version](https://github.com/wwt/SwiftCurrent/blob/main/.github/CONTRIBUTING.md#versioning)?

### CODE REVIEW

**Comment by Richard-Gist** [comment]
EOD: Looks like the repo we are using to validate has something weird set up wrong in the Watch app for Cocoapods.  When I converted @wiemerm 's project to a Cocoapod project, watch ran for me.

We may consider dropping watchOS support in CocoaPods for now so we can push this out, but also we could fix it for 12.4.  We could also just set the watch version high enough that you need 12.5 to use it?

**Review by morganzellers — DISMISSED** [review]

**Comment by morganzellers** [comment]
> EOD: Looks like the repo we are using to validate has something weird set up wrong in the Watch app for Cocoapods. When I converted @wiemerm 's project to a Cocoapod project, watch ran for me.
> 
> We may consider dropping watchOS support in CocoaPods for now so we can push this out, but also we could fix it for 12.4. We could also just set the watch version high enough that you need 12.5 to use it?

I would be up for dropping it in CocoaPods temporarily or bumping the version high enough to get past 12.4. I know @Tyler-Keith-Thompson  had a few ideas yesterday of how to get around the XCTest build error. Maybe we could circle back with one of those approaches in the future

**Comment by wiemerm** [comment]
> We may consider dropping watchOS support in CocoaPods for now so we can push this out, but also we could fix it for 12.4. We could also just set the watch version high enough that you need 12.5 to use it?

Regardless of whether CocoaPods remove(d/s) support for watchOS, we should go ahead and bump the `Package.swift` file watchOS support to be high enough to need 12.5 (watchOS 74). Either we gain that you can't use SwiftCurrent to build watchOS apps prior to that version (and therefore on Xcode pre-12.5) or we at least have an indicator that we can't guarantee it's usable prior to that version.

**Review by morganzellers — APPROVED** [review]

**Comment by Richard-Gist** [comment]
Things still missing in this, updating the supported versions doc (SECURITY.md).  And we need the SPM validation step to actually validate these things as well.

**Comment by Richard-Gist** [comment]
EOD: I can't figure out how to use swift build to build against macOS and the same for trying to build against certain destinations.  I would really want this to work:

```swift
# Confirm OrchestrationResponders can build for their destinations
    sh('xcodebuild -scheme SwiftCurrent_UIKit')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk iphonesimulator -destination"platform=iOS Simulator,name=iPhone 12"')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk appletvsimulator -destination"platform=tvOS Simulator,name=Apple TV"')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk macosx -ARCHS="x86_64h" -destination"platform=macOS,variant=Mac Catalyst"')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk iphonesimulator -destination"platform=macOS,variant=Mac Catalyst"')
```

I have done a lot to try and curate things a little more into better testing.

**Comment by Richard-Gist** [comment]
EOD: I can't figure out how to use swift build to build against macOS and the same for trying to build against certain destinations.  I would really want this to work:

```swift
# Confirm OrchestrationResponders can build for their destinations
    sh('xcodebuild -scheme SwiftCurrent_UIKit')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk iphonesimulator -destination"platform=iOS Simulator,name=iPhone 12"')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk appletvsimulator -destination"platform=tvOS Simulator,name=Apple TV"')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk macosx -ARCHS="x86_64h" -destination"platform=macOS,variant=Mac Catalyst"')
    sh('xcodebuild -scheme SwiftCurrent_UIKit -sdk iphonesimulator -destination"platform=macOS,variant=Mac Catalyst"')
```

I have done a lot to try and curate things a little more into better testing.

**Review by morganzellers — APPROVED** [review]

**Review by wiemerm — APPROVED** [review]

**Pull request merged**
