### PR TITLE
Upping version of SwiftSyntax in the CLI to lastest.

### PR DESCRIPTION
**Pull request by morganzellers**
## Checklist:
- [x] Did you sign the [Contributor License Agreement](https://cla-assistant.io/wwt/SwiftCurrent)?
- [x] Is the linter reporting 0 errors?
- [ ] Does the CI pipeline pass?

### CODE REVIEW

**Review by Tyler-Keith-Thompson — CHANGES_REQUESTED** [review]
This requires consumers to use Swift 5.6, why would we place that restriction on them?

**Comment by morganzellers** [comment]
Testing these changes as local packages fixed the problems seen in the issue. Not sure what the difference is, but the version we were using was a handful of months behind. The [release page](https://github.com/apple/swift-syntax/releases/tag/0.50600.1) mentions vending the internal parser library as a binary framework on macOS, but 🤷🏻.

**Comment by morganzellers** [comment]
> This requires consumers to have Swift 5.6, why would we place that restriction on them?

Ah, yeah I didn't consider that.

**Review by Tyler-Keith-Thompson — APPROVED** [review]
With the understanding that this change took us from "it doesn't work" to "it works" I think accepting Swift 5.6 makes sense.

**Pull request merged**
